// regression/svelte/fixtures/valid.svelte
<script>
  function greet(name) {
    return `Hello, ${name}!`;
  }

  function farewell(name) {
    return `Goodbye, ${name}!`;
  }

  class Calculator {
    add(a, b) {
      return a + b;
    }
    subtract(a, b) {
      return a - b;
    }
  }

  const result = greet("World");
</script>

<h1>{result}</h1>

// regression/vue/fixtures/valid.vue
<script>
function greet(name) {
  return `Hello, ${name}!`;
}

function farewell(name) {
  return `Goodbye, ${name}!`;
}

class Calculator {
  add(a, b) {
    return a + b;
  }
  subtract(a, b) {
    return a - b;
  }
}

greet("World");
</script>

<template>
  <div class="container">
    <h1>{{ greet('World') }}</h1>
  </div>
</template>

<style scoped>
.container { padding: 1rem; }
</style>
